import { Inter } from "next/font/google";
import "../styles/globals.css";
import { CssBaseline } from '@mui/material';
import Head from 'next/head';
import type { ReactNode } from 'react';

interface Metadata {
  title: string;
  description: string;
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </Head>
      <body className={inter.className}>
        <CssBaseline />
        {children}
      </body>
    </html>
  );
}
